
server:
  port: 8083
# 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug
    root: info
spring:
  profiles:
    active: local
  main:
    allow-circular-references: true
  redis:
    host: ${REDIS_HOST:ubuntu.wsl}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:password}
    lettuce:
      pool:
        max-active: 300

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:ubuntu.wsl}:${DATASOURCE_PORT:3306}/sc_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://ubuntu.wsl:${DATASOURCE_PORT:3306}/sc_admin?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password}
authorizes:
  ListMetaData:
    - patterns: /menu/*
      httpMethods: GET
      roles: ADMIN
    - patterns: /menu
      httpMethods: GET
      roles: USER
